[package]
name = "api"
version = "1.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "api"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
axum = { version = "0.6.20", features = ["headers", "tracing"] }
chrono = { version = "0.4.30", default-features = false, features = ["std"] }
config = "0.13.3"
delay_timer = { git = "https://github.com/MorganTwoZero/delay-timer.git" }
dotenvy = "0.15.7"
futures = "0.3.28"
futures-util = "0.3.28"
hyper = "0.14.27"
regex = "1.9.3"
reqwest = { version = "0.11.19", default-features = false, features = [
    "json",
    "rustls-tls",
    "stream",
] }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
serde-aux = { version = "4.2.0", default-features = false }
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["macros", "rt"] }
tower-http = { version = "0.4.3", features = ["trace", "fs"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }

# local deps
config-builder = { path = "../config-builder" }
config-structs = { path = "../config-structs" }
embed = { path = "../embed" }
errors = { path = "../errors" }
etl = { path = "../etl" }
tele = { path = "../tele" }

[dependencies.uuid]
version = "1.4.1"
features = ["v4", "fast-rng", "macro-diagnostics", "serde"]

[dependencies.sqlx]
version = "0.7.1"
default-features = false
features = ["runtime-tokio-rustls", "macros", "postgres", "migrate"]

[dev-dependencies]
once_cell = "1.18.0"
serde_path_to_error = "0.1.14"
wiremock = "0.5.19"
