[package]
name = "pic-scraper-backend"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "pic-scraper-backend"

[dependencies]
axum = { version = "0.6.12", features = ["headers"] }
hyper = "0.14.25"
tower-http = { version = "0.4.0", features = ["trace", "fs"] }
tokio = { version = "1.26.0", features = ["macros", "rt"] }
config = "0.13.3"
serde = { version = "1.0.158", features = ["derive"] }
serde-aux = "4.1.2"
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.16", features = [
    "registry",
    "env-filter",
] }
tracing-bunyan-formatter = "0.3.6"
tracing-log = "0.1.3"
secrecy = { version = "0.8.0", features = ["serde"] }
chrono = { version = "0.4.24", features = ["std"] }
reqwest = { version = "0.11.15", default-features = false, features = [
    "json",
    "rustls-tls",
] }
thiserror = "1.0.40"
anyhow = "1.0.70"
futures = "0.3.27"
scraper = "0.15.0"
async-trait = "0.1.68"
bytes = "1.4.0"

[dependencies.uuid]
version = "1.3.0"
features = ["v4", "fast-rng", "macro-diagnostics", "serde"]

[dependencies.sqlx]
version = "0.6.3"
default-features = false
features = ["runtime-actix-rustls", "macros", "postgres", "migrate", "offline"]

[dev-dependencies]
once_cell = "1.17.1"
serde_json = "1.0.94"
