[package]
name = "pic-scraper-backend"
version = "1.1.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "pic-scraper-backend"

[dependencies]
axum = { version = "0.6.18", features = ["headers", "tracing"] }
hyper = "0.14.26"
tower-http = { version = "0.4.0", features = ["trace", "fs"] }
tokio = { version = "1.28.0", features = ["macros", "rt"] }
config = "0.13.3"
serde = { version = "1.0.162", features = ["derive"] }
serde-aux = { version = "4.2.0", default-features = false }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
tracing-bunyan-formatter = "0.3.7"
tracing-log = "0.1.3"
secrecy = { version = "0.8.0", features = ["serde"] }
chrono = { version = "0.4.24", default-features = false, features = ["std"] }
reqwest = { version = "0.11.17", default-features = false, features = [
    "json",
    "rustls-tls",
    "stream",
] }
thiserror = "1.0.40"
anyhow = "1.0.71"
futures = "0.3.28"
scraper = "0.16.0"
async-trait = "0.1.68"
futures-util = "0.3.28"
regex = "1.8.1"
serde_json = "1.0.96"
delay_timer = { git = "https://github.com/MorganTwoZero/delay-timer.git" }
dotenvy = "0.15.7"
tonic = { version = "0.8.3", features = ["tls", "tls-roots"] }
tracing-opentelemetry = { git = "https://github.com/jaysonsantos/tracing-opentelemetry.git", branch = "update-opentelemetry-0.19" }
opentelemetry-otlp = { version = "0.12", features = ["reqwest-client", "reqwest-rustls", "http-proto", "tls"] }
opentelemetry = { version = "0.19", default-features = false, features = [ "trace", "rt-tokio" ] }

[dependencies.uuid]
version = "1.3.2"
features = ["v4", "fast-rng", "macro-diagnostics", "serde"]

[dependencies.sqlx]
version = "0.6.3"
default-features = false
features = ["runtime-actix-rustls", "macros", "postgres", "migrate", "offline"]

[dev-dependencies]
once_cell = "1.17.1"
wiremock = "0.5.18"
