[package]
name = "pic-scraper-backend"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "pic-scraper-backend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.10"
tower = "0.4.13"
hyper = "0.14.24"
tower-http = { version = "0.4.0", features = ["trace", "fs"] }
tokio = { version = "1.26.0", features = ["macros", "rt"] }
config = "0.13.3"
serde = { version = "1.0.152", features = ["derive"] }
serde-aux = "4.1.2"
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.16", features = [
    "registry",
    "env-filter",
] }
tracing-bunyan-formatter = "0.3.6"
tracing-log = "0.1.3"
tracing-actix-web = "0.7.2"
secrecy = { version = "0.8.0", features = ["serde"] }
chrono = { version = "0.4.23", features = ["std"] }
unicode-segmentation = "1.10.1"
validator = { version = "0.16.0", features = ["derive"] }
fake = "2.5.0"
reqwest = { version = "0.11.14", default-features = false, features = [
    "json",
    "rustls-tls",
    "cookies",
] }
rand = { version = "0.8.5", features = ["std_rng"] }
thiserror = "1.0.38"
anyhow = "1.0.69"
urlencoding = "2.1.2"
htmlescape = "0.3.1"
serde_json = "1.0.93"
futures-util = "0.3.26"
serde_urlencoded = "0.7.1"

[dependencies.uuid]
version = "1.3.0"
features = ["v4", "fast-rng", "macro-diagnostics", "serde"]

[dependencies.sqlx]
version = "0.6.2"
default-features = false
features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "time",
    "migrate",
    "offline",
]

[dev-dependencies]
once_cell = "1.17.1"
claims = "0.7.1"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
wiremock = "0.5.17"
serde_json = "1.0.93"
linkify = "0.9.0"
