version: '3'

services:
  db:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    image: postgres:15.1-alpine
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres  -d postgres'"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  web:
    environment:
      - APP_ENVIRONMENT=local
      - APP_app__api_client_headers__cookie
      - APP_app__api_client_headers__authorization
      - APP_app__api_client_headers__csrf_token
    build: .
    volumes:
      - ./config:/home/nonroot/config:ro
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "8000:8000"