version: '3'

services:
  db-stage:
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:15.1-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 5s
      timeout: 10s
      retries: 10

  web:
    environment:
      - APP_ENVIRONMENT=stage
      - APP_database__password=${POSTGRES_PASSWORD}

      - APP_app__headers__cookie
      - APP_app__headers__authorization
      - APP_app__headers__csrf_token

      - VIRTUAL_HOST=stage.pixiv.sbs,www-stage.pixiv.sbs
      - VIRTUAL_PORT=8001
      - LETSENCRYPT_HOST=stage.pixiv.sbs,www-stage.pixiv.sbs

      - RUST_LOG
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME
      - OTEL_TRACES_SAMPLER
      
    restart: unless-stopped
    image: morgan20/pic-scraper-backend:stage
    command: /api
    volumes:
      - ./config:/home/nonroot/config:ro
    depends_on: 
      db-stage:
        condition: service_healthy
    ports:
      - 8001:8001

  scraper:
    environment:
      - APP_ENVIRONMENT=stage
      - APP_database__password=${POSTGRES_PASSWORD}

      - APP_app__api_client_headers__cookie
      - APP_app__api_client_headers__authorization
      - APP_app__api_client_headers__csrf_token

      - RUST_LOG
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME
      - OTEL_TRACES_SAMPLER

    restart: unless-stopped
    image: morgan20/pic-scraper-backend:stage
    command: /scraper
    volumes:
      - ./config:/home/nonroot/config:ro
      - ./headers.txt:/home/nonroot/headers.txt:ro
    depends_on: 
      db-stage:
        condition: service_healthy

networks:
  default:
    external: true
    name: net
