version: '3'

services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: post
      POSTGRES_PASSWORD: POSTGRES_PASSWORD # is it working now?
    image: postgres:15.1-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d post'"]
      interval: 1s
      timeout: 5s
      retries: 10

  web:
    environment:
      APP_POSTGRES_PASSWORD: POSTGRES_PASSWORD
    restart: on-failure
    image: morgan20/pic-scraper-backend
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "8000:8000"