version: '3'

services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: post
      POSTGRES_PASSWORD: password
    image: postgres:15.1-alpine
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  web:
    environment:
      APP_ENVIRONMENT: local
    restart: on-failure
    image: morgan20/pic-scraper-backend
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "8000:8000"