[package]
name = "etl"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "scraper"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
axum = { version = "0.6.20", default-features = false }
chrono = { version = "0.4.30", default-features = false, features = ["std"] }
config = "0.13.3"
delay_timer = { git = "https://github.com/MorganTwoZero/delay-timer.git" }
dotenvy = "0.15.7"
futures = "0.3.28"
hyper = "0.14.27"
reqwest = { version = "0.11.19", default-features = false, features = ["json"] }
scraper = "0.17.1"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
sqlx = { version = "0.7.1", default-features = false, features = ["postgres", "macros", "runtime-tokio-rustls", "chrono"] }
tokio = { version = "1.32.0", features = ["macros", "rt"] }
tracing = { version = "0.1.37", features = ["log"] }

# local deps
config-builder = { path = "../config-builder" }
config-structs = { path = "../config-structs" }
errors = { path = "../errors" }
tele = { path = "../tele" }

[dev-dependencies]
serde_path_to_error = "0.1.14"