[package]
name = "etl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
errors = { path = "../errors" }
config_structs = { path = "../config-structs" }
sqlx = { version = "0.7.1", default-features = false, features = ["postgres", "macros", "runtime-tokio-rustls"] }
axum = { version = "0.6.19", default-features = false }
serde = { version = "1.0.183", features = ["derive"] }
tracing = { version = "0.1.37", features = ["log"] }
reqwest = { version = "0.11.18", default-features = false, features = ["json"] }
futures = "0.3.28"
chrono = { version = "0.4.26", default-features = false, features = ["std"] }
async-trait = "0.1.72"
scraper = "0.17.1"
serde_json = "1.0.104"

[dev-dependencies]
serde_path_to_error = "0.1.14"