app:
  port: 8000
  base_url: "http://127.0.0.1"
  blacklist:
    tags: ["COM3D2", "mikumikudance", "mmd", "R18MMD", "崩坏3MMD", "コイカツ", "NTR", "動圖", "R-18G", "コイカツ!", "うごイラ", "3D", "koikatsu!", "Koikatsu", "Koikatsu!", "恋活", "3DCG", "MMD", "王者荣耀", "斗破苍穹", "koikatsu"]
    authors: ["220013874", "蘭夜ノ观星", "daotong道童", "星河Mikly", "FTzur", 鱼生子子生片", "妊娠", "催眠", "ヒカマニ", "Hikakin_Mania", "巨大娘", "Vulcax", "hendienuns", "寂静之刃", "Arise", "Tomodachi", "梦醒幻实", "AbilfloridaArts", "四奈乃", "云起", "極彩色", "阡陌菌", "千樺·エイミー・ザル", "Trishnicajoy", "PShiro", "黑虎阿符", "BT1", "BALD", "Tay-X", "Meigane", "过度解毒", "「雪」", "资源出口", "阿曼達·木子", "MilkMan29", "興趣使然", "肉乎乎の布洛妮娅", "孤人GuRn", " 哎呀_迷路了_迷路了__"]
database:
  port: 5432
  username: "postgres"
  database_name: "post"