app:
  headers:
    # setting mock values to pass the embed tests in GH action
    cookie: "test"
    authorization: "test"
    csrf_token: "test"
  port: 8000
  blacklist:
    tags: ["COM3D2", "mikumikudance", "mmd", "R18MMD", "崩坏3MMD", "コイカツ", "NTR", "動圖", "R-18G", "コイカツ!", "うごイラ", "3D", "koikatsu!", "Koikatsu", "Koikatsu!", "恋活", "3DCG", "MMD", "王者荣耀", "斗破苍穹", "koikatsu"]
    authors: ["pyeong_il 평일", "千樺·ネフォトリア", "蓝莓蛋糕", "scp096qwq", "220013874", "蘭夜ノ观星", "daotong道童", "星河Mikly", "FTzur", 鱼生子子生片", "妊娠", "催眠", "ヒカマニ", "Hikakin_Mania", "巨大娘", "Vulcax", "hendienuns", "寂静之刃", "Arise", "Tomodachi", "梦醒幻实", "AbilfloridaArts", "四奈乃", "云起", "極彩色", "阡陌菌", "千樺·エイミー・ザル", "Trishnicajoy", "PShiro", "黑虎阿符", "BT1", "BALD", "Tay-X", "Meigane", "过度解毒", "「雪」", "资源出口", "阿曼達·木子", "MilkMan29", "興趣使然", "肉乎乎の布洛妮娅", "孤人GuRn", " 哎呀_迷路了_迷路了__"]
  sources_urls: 
    pixiv: "https://www.pixiv.net/touch/ajax/search/illusts?include_meta=1&type=illust_and_ugoira&word=崩坏3rd OR 崩壊3rd OR 崩坏3 OR 崩壞3rd OR honkaiimpact3rd OR 붕괴3 OR 붕괴3rd OR 崩坏学园 OR 崩壊学園 OR 崩坏 OR 崩坏三 OR リタ・ロスヴァイセ OR 琪亚娜 OR 符华 OR フカ OR 希儿&s_mode=s_tag_full&lang=en"
    pixiv_details: "https://www.pixiv.net/touch/ajax/illust/details?illust_id="
    pixiv_image: "https://i.pximg.net/img-master"
    twitter_honkai: "https://api.twitter.com/1.1/search/tweets.json?result_type=recent&count=100&q=%23%E7%AC%A6%E5%8D%8E%20OR%20%23%E5%B4%A9%E5%9D%8F3%20OR%20%23%E3%83%95%E3%82%AB%20OR%20%23%E5%B4%A9%E5%9D%8F3rd%20OR%20%23%E5%B4%A9%E5%A3%9E3rd%20OR%20%23%EB%B6%95%EA%B4%B43rd%20OR%20%23Honkaiimpact3rd%20OR%20%23%E5%B4%A9%E5%A3%8A3rd%20min_faves%3A2"
    twitter_home: "https://api.twitter.com/1.1/statuses/home_timeline.json?tweet_mode=extended&exclude_replies=1&include_rts=0&count=200"
    mihoyo: "https://bbs-api.mihoyo.com/post/wapi/getForumPostList?forum_id=4&gids=1&is_good=false&is_hot=false&page_size=20&sort_type=2"
    bcy: "https://bcy.net/apiv3/common/circleFeed?circle_id=109315&since=0&sort_type=2&grid_type=10"
    lofter: "https://www.lofter.com/tag/"
database:
  port: 5432
  username: "postgres"
  database_name: "postgres"