[package]
name = "tele"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", features = [ "matched-path", "original-uri", "tokio" ] }
opentelemetry = { version = "0.20.0", default-features = false, features = [ "trace", "rt-tokio" ] }
opentelemetry-otlp = { version = "0.13.0", features = ["reqwest-client", "reqwest-rustls", "http-proto", "tls"] }
tonic = { version = "0.9.2", features = ["tls", "tls-roots"] }
tower-http = { version = "0.4.3", features = ["trace", "fs"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-opentelemetry = "0.20.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }