[package]
name = "embed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.19", features = ["headers", "tracing"] }
futures = "0.3.28"
regex = "1.9.1"
serde_json = "1.0.104"
serde = { version = "1.0.185", features = ["derive"] }
reqwest = { version = "0.11.18", default-features = false, features = [
    "json",
    "rustls-tls",
    "stream",
] }
tracing = { version = "0.1.37", features = ["log"] }
hyper = "0.14.27"
anyhow = "1.0.72"
errors = { path = "../errors" }
config_structs ={ path = "../config-structs" }