[package]
name = "errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.19", features = ["headers"] }
reqwest = { version = "0.11.18", default-features = false }
thiserror = "1.0.44"
anyhow = "1.0.72"
delay_timer = { git = "https://github.com/MorganTwoZero/delay-timer.git" }
serde = { version = "1.0.183", default-features = false }
serde-aux = { version = "4.2.0", default-features = false }
tracing = { version = "0.1.37", default-features = false }

[dependencies.sqlx]
version = "0.7.1"
default-features = false